title: Moss
description: Agent harness for Go
logo: https://avatars.githubusercontent.com/u/268767877
theme: minima
markdown: kramdown
header_pages: []
kramdown:
  input: GFM
plugins:
  - jekyll-feed

